# Group 4 Homework 7-  SHAWN's NOTEBOOK
### Our data set is looking at batting statistics for baseball from the 1800's through current.

In [273]:
#Import the various tools that we will need as we plot our different types of graphs.  I am commenting these out as this assignmment does not require visualizations
# %matplotlib inline
# import matplotlib as mpl
# import matplotlib.pyplot as plt
# import seaborn as sns
# import plotly.express as px
import pandas as pd
import numpy as np
# import plotly.graph_objects as go

## Import the data from GitHub

In [274]:
baseballstats = pd.read_csv("https://raw.githubusercontent.com/zoberender/Python-Group-Project/master/Batting.csv")
#It is important to convert NaN to 0 to get calculations to function correctly
baseballstats['IBB'] = baseballstats['IBB'].fillna(0)
baseballstats['HBP'] = baseballstats['HBP'].fillna(0)
baseballstats['SH'] = baseballstats['SH'].fillna(0)
baseballstats['SF'] = baseballstats['SF'].fillna(0)
# Create new column to calculate average
baseballstats["AVG"] = baseballstats["H"]/baseballstats["AB"]
# Create new column to calculate total bases
baseballstats["TB"] = baseballstats["H"] - baseballstats["2B"] - baseballstats["3B"] - baseballstats["HR"] + 2*baseballstats["2B"] + 3*baseballstats["3B"]+4*baseballstats["HR"]
# Slugging is Total Bases/At bats
baseballstats["SLG"] = baseballstats["TB"]/baseballstats["AB"]
#Plate Appearances to calculate OBP
baseballstats["PA"] = baseballstats["AB"] + baseballstats["BB"] + baseballstats["HBP"] + baseballstats["SF"]
#On Base Percentage = Times on base/Plat Appearances
baseballstats["OBP"] = (baseballstats["H"]+baseballstats["BB"]+baseballstats["HBP"])/baseballstats["PA"]
#OBP + SLUGGING IS A GREAT WAY TO MEASURE OVERALL PLAYER VALUE
baseballstats["OPS"] = baseballstats["OBP"] + baseballstats["SLG"]
#ISOLATED POWER IS A WAY TO MEASURE A PLAYER'S OVERALL POWER WHY TAKING OUT THE IMPACT OF BATTING AVERAGE
baseballstats['ISP'] = baseballstats['SLG'] - baseballstats['AVG']
#Add 1B as its own column.  1B = HR - (2B + 3B + HR)
baseballstats["1B"] = baseballstats["H"] - baseballstats["2B"] - baseballstats["3B"] - baseballstats["HR"]
#Add ERA to the data fram using by binning
cut_label = ['19th Century','Dead Ball','Live Ball','Integration','Divisional','Steroid','Current']
cut_bins = [0,1899,1919,1946,1968,1993,2007,max(baseballstats['yearID'])]
baseballstats['ERA'] = pd.cut(baseballstats['yearID'], bins=cut_bins, labels = cut_label)
#Filter for Plate Appearances greater than 200 to eliminate the lower volume plate appearances.
baseballstats = baseballstats[(baseballstats["PA"] >= 200)]

baseballstats

,playerID,yearID,Stint,teamID,lgID,G,AB,R,H,2B,...,TEAM NAME,AVG,TB,SLG,PA,OBP,OPS,ISP,1B,ERA
118,ansonca01,1872,1,PH1,NaN,46,217,60,90,10,...,PNA-Philadelphia Athletics,0.414747,114,0.525346,233.0,0.454936,0.980281,0.110599,73,19th Century
121,barnero01,1872,1,BS1,NaN,45,230,81,99,28,...,BNA-Boston Red Stockings,0.430435,134,0.582609,239.0,0.451883,1.034492,0.152174,68,19th Century
125,bechtge01,1872,1,NY2,NaN,51,247,61,74,11,...,NNA-New York Mutuals,0.299595,91,0.368421,254.0,0.318898,0.687319,0.068826,60,19th Century
144,cummica01,1872,1,NY2,NaN,55,249,37,52,9,...,NNA-New York Mutuals,0.208835,67,0.269076,253.0,0.221344,0.490420,0.060241,40,19th Century
145,cuthbne01,1872,1,PH1,NaN,47,260,83,88,10,...,PNA-Philadelphia Athletics,0.338462,101,0.388462,266.0,0.353383,0.741845,0.050000,77,19th Century
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107243,wolteto01,2019,1,COL,NL,121,359,42,94,17,...,COL-Colorado Rockies,0.261838,118,0.328691,409.0,0.337408,0.666099,0.066852,74,Current
107246,wongko01,2019,1,SLN,NL,148,478,61,136,25,...,STL-St. Louis Cardinals,0.284519,202,0.422594,543.0,0.360958,0.783552,0.138075,96,Current
107262,yastrmi01,2019,1,SFN,NL,107,371,64,101,22,...,SFG-San Francisco Giants,0.272237,192,0.517520,410.0,0.334146,0.851667,0.245283,55,Current
107264,yelicch01,2019,1,MIL,NL,130,489,100,161,29,...,MIL-Milwaukee Brewers,0.329243,328,0.670757,580.0,0.429310,1.100067,0.341513,85,Current
107277,zuninmi01,2019,1,TBA,AL,90,266,30,44,10,...,TBD-Tampa Bay Rays,0.165414,83,0.312030,289.0,0.231834,0.543864,0.146617,24,Current

# Prepare the data

In [275]:
baseballstats.shape #This shows number of rows and columns

(30669, 34)

In [276]:
baseballstats.info() #This provides the number of non-null values for each category, as well as Data Type.  Must convert objects to integers

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30669 entries, 118 to 107277
Data columns (total 34 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   playerID   30669 non-null  object
 1   yearID     30669 non-null  int64
 2   Stint      30669 non-null  int64
 3   teamID     30669 non-null  object
 4   lgID       30477 non-null  object
 5   G          30669 non-null  int64
 6   AB         30669 non-null  int64
 7   R          30669 non-null  int64
 8   H          30669 non-null  int64
 9   2B         30669 non-null  int64
 10  3B         30669 non-null  int64
 11  HR         30669 non-null  int64
 12  RBI        30480 non-null  float64
 13  SB         29716 non-null  float64
 14  CS         22736 non-null  float64
 15  BB         30669 non-null  int64
 16  SO         30027 non-null  float64
 17  IBB        30669 non-null  float64
 18  HBP        30669 non-null  float64
 19  SH         30669 non-null  float64
 20  SF         30669 non-null  float64
 21  GIDP       21910 non-null  float64
 22  AGE        30669 non-null  int64
 23  FULL NAME  30669 non-null  object
 24  TEAM NAME  30669 non-null  object
 25  AVG        30669 non-null  float64
 26  TB         30669 non-null  int64
 27  SLG        30669 non-null  float64
 28  PA         30669 non-null  float64
 29  OBP        30669 non-null  float64
 30  OPS        30669 non-null  float64
 31  ISP        30669 non-null  float64
 32  1B         30669 non-null  int64
 33  ERA        30669 non-null  category
dtypes: category(1), float64(15), int64(13), object(5)
memory usage: 8.0+ MB

In [277]:
baseballstats['OPS'].unique()

array([0.98028124, 1.03449154, 0.68731869, ..., 0.85166656, 1.10006699,
       0.54386399])

In [278]:
baseballstats['ERA'].unique()

['19th Century', 'Dead Ball', 'Live Ball', 'Integration', 'Divisional', 'Steroid', 'Current']
Categories (7, object): ['19th Century' < 'Dead Ball' < 'Live Ball' < 'Integration' < 'Divisional' < 'Steroid' < 'Current']

In [279]:
baseballstats['TEAM NAME'].unique()

array(['PNA-Philadelphia Athletics', 'BNA-Boston Red Stockings',
       'NNA-New York Mutuals', 'BLC-Baltimore Canaries',
       'BRA-Brooklyn Atlantics', 'PWS-Philadelphia Whites',
       'HNA-Hartford Dark Blues', 'CNA-Chicago White Stockings',
       'SNA-St. Louis Brown Stockings', 'CHC-Chicago Cubs',
       'SBS-St. Louis Brown Stockings', 'CNR-Cincinnati Reds',
       'HAR-Hartford Dark Blues', 'ATH-Philadelphia Athletics',
       'NYU-New York Mutuals', 'LGR-Louisville Grays',
       'ATL-Atlanta Braves', 'PRO-Providence Grays',
       'IBL-Indianapolis Blues', 'MLG-Milwaukee Grays',
       'TRT-Troy Trojans', 'CBL-Cleveland Blues', 'SYR-Syracuse Stars',
       'BUF-Buffalo Bisons', 'WOR-Worcester Ruby Legs',
       'DTN-Detroit Wolverines', 'PHA-Philadelphia Athletics',
       'LOU-Louisville Colonels', 'CIN-Cincinnati Reds',
       'STL-St. Louis Cardinals', 'BLO-Baltimore Orioles',
       'PIT-Pittsburgh Pirates', 'NYP-New York Metropolitans',
       'CBK-Columbus Buckeyes', 'SFG-San Francisco Giants',
       'PHI-Philadelphia Phillies', 'SLM-St. Louis Maroons',
       'WNA-Washington Nationals', 'COR-Cincinnati Outlaw Reds',
       'TOL-Toledo Blue Stockings', 'BRD-Boston Reds',
       'LAD-Los Angeles Dodgers', 'CPI-Chicago/Pittsburgh (Union League)',
       'WST-Washington Nationals', 'PHK-Philadelphia Keystones',
       'BLU-Baltimore Monumentals', 'IHO-Indianapolis Hoosiers',
       'WNL-Washington Nationals', 'KCN-Kansas City Cowboys',
       'CLV-Cleveland Spiders', 'IND-Indianapolis Hoosiers',
       'KCC-Kansas City Cowboys', 'CLS-Columbus Solons',
       'TLM-Toledo Maumees', "BWW-Brooklyn Ward's Wonders",
       'CHP-Chicago Pirates', 'ROC-Rochester Broncos',
       'PBB-Pittsburgh Burghers', 'BFB-Buffalo Bisons',
       'BRG-Brooklyn Gladiators', 'CLI-Cleveland Infants',
       'SYS-Syracuse Stars', 'BRS-Boston Reds', 'NYI-New York Giants',
       'PHQ-Philadelphia Athletics', 'WAS-Washington Senators',
       "CKK-Cincinnati Kelly's Killers", 'BAL-Baltimore Orioles',
       'DET-Detroit Tigers', 'CLE-Cleveland Indians',
       'NYY-New York Yankees', 'MIN-Minnesota Twins',
       'BOS-Boston Red Sox', 'OAK-Oakland Athletics',
       'CHW-Chicago White Sox', 'BFL-Buffalo Blues',
       'BTT-Brooklyn Tip-Tops', 'BLT-Baltimore Terrapins',
       'CHH-Chicago Whales', 'PBS-Pittsburgh Rebels',
       'SLI-St. Louis Terriers', 'NEW-Newark Pepper',
       'KCP-Kansas City Packers', 'ANA-Los Angeles Angels of Anaheim',
       'TEX-Texas Rangers', 'HOU-Houston Astros', 'NYM-New York Mets',
       'KCR-Kansas City Royals', 'SDP-San Diego Padres',
       'WSN-Washington Nationals', 'MIL-Milwaukee Brewers',
       'TOR-Toronto Blue Jays', 'SEA-Seattle Mariners',
       'FLA-Miami Marlins', 'COL-Colorado Rockies',
       'ARI-Arizona Diamondbacks', 'TBD-Tampa Bay Rays'], dtype=object)

In [280]:
# Include columns of interest on this line
columns = ["OPS","lgID", "TEAM NAME", "AGE", "PA", "ISP", "ERA"]
columns

['OPS', 'lgID', 'TEAM NAME', 'AGE', 'PA', 'ISP', 'ERA']

In [281]:
# Get the columns we actually care about
baseballstats = baseballstats[columns]
# Pay attention to the number of non-null counts.
baseballstats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30669 entries, 118 to 107277
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OPS        30669 non-null  float64
 1   lgID       30477 non-null  object
 2   TEAM NAME  30669 non-null  object
 3   AGE        30669 non-null  int64
 4   PA         30669 non-null  float64
 5   ISP        30669 non-null  float64
 6   ERA        30669 non-null  category
dtypes: category(1), float64(3), int64(1), object(2)
memory usage: 1.7+ MB

In [282]:
#Drop out the NA values
baseballstats.dropna(inplace=True)
baseballstats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30477 entries, 685 to 107277
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OPS        30477 non-null  float64
 1   lgID       30477 non-null  object
 2   TEAM NAME  30477 non-null  object
 3   AGE        30477 non-null  int64
 4   PA         30477 non-null  float64
 5   ISP        30477 non-null  float64
 6   ERA        30477 non-null  category
dtypes: category(1), float64(3), int64(1), object(2)
memory usage: 1.7+ MB

<ipython-input-282-5fce26f8aa37>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [283]:
#Get dummy variables for team name
pd.get_dummies(baseballstats[["TEAM NAME"]], prefix_sep= "::", drop_first = True)

,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,TEAM NAME::BLO-Baltimore Orioles,TEAM NAME::BLT-Baltimore Terrapins,TEAM NAME::BLU-Baltimore Monumentals,TEAM NAME::BOS-Boston Red Sox,...,TEAM NAME::TLM-Toledo Maumees,TEAM NAME::TOL-Toledo Blue Stockings,TEAM NAME::TOR-Toronto Blue Jays,TEAM NAME::TRT-Troy Trojans,TEAM NAME::WAS-Washington Senators,TEAM NAME::WNA-Washington Nationals,TEAM NAME::WNL-Washington Nationals,TEAM NAME::WOR-Worcester Ruby Legs,TEAM NAME::WSN-Washington Nationals,TEAM NAME::WST-Washington Nationals
685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
686,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107246,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107262,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107264,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107277,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [284]:
#Get dummy variables for league
pd.get_dummies(baseballstats[["lgID"]], prefix_sep= "::", drop_first = True)

        lgID::AL  lgID::FL  lgID::NL  lgID::PL  lgID::UA
685            0         0         1         0         0
686            0         0         1         0         0
687            0         0         1         0         0
692            0         0         1         0         0
694            0         0         1         0         0
...          ...       ...       ...       ...       ...
107243         0         0         1         0         0
107246         0         0         1         0         0
107262         0         0         1         0         0
107264         0         0         1         0         0
107277         1         0         0         0         0

[30477 rows x 5 columns]

In [285]:
# Get dummy variables for Era
pd.get_dummies(baseballstats[["ERA"]], prefix_sep= "::", drop_first = True)

,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current
685,0,0,0,0,0,0
686,0,0,0,0,0,0
687,0,0,0,0,0,0
692,0,0,0,0,0,0
694,0,0,0,0,0,0
...,...,...,...,...,...,...
107243,0,0,0,0,0,1
107246,0,0,0,0,0,1
107262,0,0,0,0,0,1
107264,0,0,0,0,0,1
107277,0,0,0,0,0,1

In [286]:
# Helper function to colosidate information
def createCategoricalDummies(dataFrame, categoryList):
    return pd.get_dummies(dataFrame[categoryList], prefix_sep = "::", drop_first = True)

In [287]:
categories = ["TEAM NAME", "lgID", "ERA"]

baseballstats = pd.concat(
    [baseballstats.drop(categories, axis=1), createCategoricalDummies(baseballstats, categories)], axis= 1)
baseballstats

,OPS,AGE,PA,ISP,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,...,lgID::FL,lgID::NL,lgID::PL,lgID::UA,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current
685,0.829900,24,321.0,0.093851,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
686,1.052050,26,342.0,0.161491,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
687,0.682370,22,289.0,0.067138,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
692,0.532268,22,266.0,0.056818,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
694,0.556756,27,281.0,0.011029,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107243,0.666099,27,409.0,0.066852,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107246,0.783552,28,543.0,0.138075,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107262,0.851667,28,410.0,0.245283,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107264,1.100067,27,580.0,0.341513,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107277,0.543864,28,289.0,0.146617,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

# Import Machine Learning Libraries for Regression and get testing and training data

In [288]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression

In [289]:
features = list(baseballstats.columns)
features.remove("OPS")
target = "OPS"

print(f"Feature categories: {features}")
print(f"Target feature: {target}")

Feature categories: ['AGE', 'PA', 'ISP', 'TEAM NAME::ARI-Arizona Diamondbacks', 'TEAM NAME::ATH-Philadelphia Athletics', 'TEAM NAME::ATL-Atlanta Braves', 'TEAM NAME::BAL-Baltimore Orioles', 'TEAM NAME::BFB-Buffalo Bisons', 'TEAM NAME::BFL-Buffalo Blues', 'TEAM NAME::BLO-Baltimore Orioles', 'TEAM NAME::BLT-Baltimore Terrapins', 'TEAM NAME::BLU-Baltimore Monumentals', 'TEAM NAME::BOS-Boston Red Sox', 'TEAM NAME::BRD-Boston Reds', 'TEAM NAME::BRG-Brooklyn Gladiators', 'TEAM NAME::BRS-Boston Reds', 'TEAM NAME::BTT-Brooklyn Tip-Tops', 'TEAM NAME::BUF-Buffalo Bisons', "TEAM NAME::BWW-Brooklyn Ward's Wonders", 'TEAM NAME::CBK-Columbus Buckeyes', 'TEAM NAME::CBL-Cleveland Blues', 'TEAM NAME::CHC-Chicago Cubs', 'TEAM NAME::CHH-Chicago Whales', 'TEAM NAME::CHP-Chicago Pirates', 'TEAM NAME::CHW-Chicago White Sox', 'TEAM NAME::CIN-Cincinnati Reds', "TEAM NAME::CKK-Cincinnati Kelly's Killers", 'TEAM NAME::CLE-Cleveland Indians', 'TEAM NAME::CLI-Cleveland Infants', 'TEAM NAME::CLS-Columbus Solons', 'TEAM NAME::CLV-Cleveland Spiders', 'TEAM NAME::CNR-Cincinnati Reds', 'TEAM NAME::COL-Colorado Rockies', 'TEAM NAME::COR-Cincinnati Outlaw Reds', 'TEAM NAME::CPI-Chicago/Pittsburgh (Union League)', 'TEAM NAME::DET-Detroit Tigers', 'TEAM NAME::DTN-Detroit Wolverines', 'TEAM NAME::FLA-Miami Marlins', 'TEAM NAME::HAR-Hartford Dark Blues', 'TEAM NAME::HOU-Houston Astros', 'TEAM NAME::IBL-Indianapolis Blues', 'TEAM NAME::IHO-Indianapolis Hoosiers', 'TEAM NAME::IND-Indianapolis Hoosiers', 'TEAM NAME::KCC-Kansas City Cowboys', 'TEAM NAME::KCN-Kansas City Cowboys', 'TEAM NAME::KCP-Kansas City Packers', 'TEAM NAME::KCR-Kansas City Royals', 'TEAM NAME::LAD-Los Angeles Dodgers', 'TEAM NAME::LGR-Louisville Grays', 'TEAM NAME::LOU-Louisville Colonels', 'TEAM NAME::MIL-Milwaukee Brewers', 'TEAM NAME::MIN-Minnesota Twins', 'TEAM NAME::MLG-Milwaukee Grays', 'TEAM NAME::NEW-Newark Pepper', 'TEAM NAME::NYI-New York Giants', 'TEAM NAME::NYM-New York Mets', 'TEAM NAME::NYP-New York Metropolitans', 'TEAM NAME::NYU-New York Mutuals', 'TEAM NAME::NYY-New York Yankees', 'TEAM NAME::OAK-Oakland Athletics', 'TEAM NAME::PBB-Pittsburgh Burghers', 'TEAM NAME::PBS-Pittsburgh Rebels', 'TEAM NAME::PHA-Philadelphia Athletics', 'TEAM NAME::PHI-Philadelphia Phillies', 'TEAM NAME::PHK-Philadelphia Keystones', 'TEAM NAME::PHQ-Philadelphia Athletics', 'TEAM NAME::PIT-Pittsburgh Pirates', 'TEAM NAME::PRO-Providence Grays', 'TEAM NAME::ROC-Rochester Broncos', 'TEAM NAME::SBS-St. Louis Brown Stockings', 'TEAM NAME::SDP-San Diego Padres', 'TEAM NAME::SEA-Seattle Mariners', 'TEAM NAME::SFG-San Francisco Giants', 'TEAM NAME::SLI-St. Louis Terriers', 'TEAM NAME::SLM-St. Louis Maroons', 'TEAM NAME::STL-St. Louis Cardinals', 'TEAM NAME::SYR-Syracuse Stars', 'TEAM NAME::SYS-Syracuse Stars', 'TEAM NAME::TBD-Tampa Bay Rays', 'TEAM NAME::TEX-Texas Rangers', 'TEAM NAME::TLM-Toledo Maumees', 'TEAM NAME::TOL-Toledo Blue Stockings', 'TEAM NAME::TOR-Toronto Blue Jays', 'TEAM NAME::TRT-Troy Trojans', 'TEAM NAME::WAS-Washington Senators', 'TEAM NAME::WNA-Washington Nationals', 'TEAM NAME::WNL-Washington Nationals', 'TEAM NAME::WOR-Worcester Ruby Legs', 'TEAM NAME::WSN-Washington Nationals', 'TEAM NAME::WST-Washington Nationals', 'lgID::AL', 'lgID::FL', 'lgID::NL', 'lgID::PL', 'lgID::UA', 'ERA::Dead Ball', 'ERA::Live Ball', 'ERA::Integration', 'ERA::Divisional', 'ERA::Steroid', 'ERA::Current']
Target feature: OPS

In [290]:
PredInput = baseballstats[features]
PredInput

,AGE,PA,ISP,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,TEAM NAME::BLO-Baltimore Orioles,...,lgID::FL,lgID::NL,lgID::PL,lgID::UA,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current
685,24,321.0,0.093851,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
686,26,342.0,0.161491,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
687,22,289.0,0.067138,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
692,22,266.0,0.056818,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
694,27,281.0,0.011029,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107243,27,409.0,0.066852,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107246,28,543.0,0.138075,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107262,28,410.0,0.245283,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107264,27,580.0,0.341513,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
107277,28,289.0,0.146617,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [291]:
OPSTarget = baseballstats[target]
OPSTarget

685       0.829900
686       1.052050
687       0.682370
692       0.532268
694       0.556756
            ...
107243    0.666099
107246    0.783552
107262    0.851667
107264    1.100067
107277    0.543864
Name: OPS, Length: 30477, dtype: float64

In [292]:
X_train, X_test, y_train, y_test = train_test_split(PredInput,OPSTarget, test_size=0.25)

print(f"Length of X_train (feature training set): {len(X_train)}")
print(f"Length of X_test (feature test set): {len(X_test)}")
print(f"Length of y_train (target training set): {len(y_train)}")
print(f"Length of y_test (target training set): {len(y_test)}")

Length of X_train (feature training set): 22857
Length of X_test (feature test set): 7620
Length of y_train (target training set): 22857
Length of y_test (target training set): 7620

# Linear Regression Model

In [293]:
lr = LinearRegression()
lr

LinearRegression()

In [294]:
lr.fit(X_train, y_train)

LinearRegression()

In [295]:
lr.score(X_train, y_train)  # What's our score with the training data set?

0.7194196480283261

In [296]:
lr.score(X_test, y_test)    # What's our score with the test data set?

0.7093134564652828

In [297]:
import math
from sklearn.metrics import explained_variance_score, mean_absolute_error, r2_score, mean_squared_error

def printMetrics(test, predictions):
    print(f"Score: {explained_variance_score(test, predictions):.2f}")
    print(f"MAE: {mean_absolute_error(test, predictions):.2f}")
    print(f"RMSE: {math.sqrt(mean_squared_error(test, predictions)):.2f}")
    print(f"r2: {r2_score(test, predictions):.2f}")

In [298]:
predictions = lr.predict(X_test)
printMetrics(y_test, predictions)

Score: 0.71
MAE: 0.05
RMSE: 0.06
r2: 0.71

In [299]:
import random as rnd
rnd.seed(1024)

In [300]:
# This would be a good way to test out random values for unknown data.  Being that our data is known, I am entering the known values.  
# numElements = 3
# samplebbstats = []
# for _ in range(numElements):
#    dict = {}
#    for column in PredInput.columns:
#        min = 0  # We'll always allow at lea
#        maxValue = round(max(baseballstats[column].values))
#        dict[column] = rnd.randint(min, maxValue)
#    samplebbstats.append(dict)
# samplebbstats

#####  I have 5 different players, and I want to see which one I expect to have the highest OPS next season
#####  Freddie Freeman is 31 years old.  He plays for the Atlanta Braves in the NL.  In his last full season, he had 692 plate appearances and his ISP was 0.254
#####  Jose Abreu is 34 years old.  He plays for the Chicago White Sox in the AL.  In his last full season, he had 693 plate appearances and his ISP was 0.219
#####  Cody Bellinger is 25 years old.  He plays for the Los Angeles Dodgers in the NL.  In his last full season, he had 661 plate appearances and his ISP was 0.324
#####  Jose Osuna is 28 years old. He plays for the Pittsburgh Pirates in the NL.  In his last full season, he had 285 plate appearances and his ISP was 0.192
#####  Aaron Judge will be 29 years old for the majority of the 2021 season.  He plays for the New York Yankees in the AL.  In his last full seaosn, he had 447 plate appearances and his ISP was 0.268

In [301]:
samplebbstats = [{'AGE': 31,
  'PA': 692,
  'ISP': 0.254,
  'TEAM NAME::ARI-Arizona Diamondbacks': 0,
  'TEAM NAME::ATH-Philadelphia Athletics': 0,
  'TEAM NAME::ATL-Atlanta Braves': 1,
  'TEAM NAME::BAL-Baltimore Orioles': 0,
  'TEAM NAME::BFB-Buffalo Bisons': 0,
  'TEAM NAME::BFL-Buffalo Blues': 0,
  'TEAM NAME::BLO-Baltimore Orioles': 0,
  'TEAM NAME::BLT-Baltimore Terrapins': 0,
  'TEAM NAME::BLU-Baltimore Monumentals': 0,
  'TEAM NAME::BOS-Boston Red Sox': 0,
  'TEAM NAME::BRD-Boston Reds': 0,
  'TEAM NAME::BRG-Brooklyn Gladiators': 0,
  'TEAM NAME::BRS-Boston Reds': 0,
  'TEAM NAME::BTT-Brooklyn Tip-Tops': 0,
  'TEAM NAME::BUF-Buffalo Bisons': 0,
  "TEAM NAME::BWW-Brooklyn Ward's Wonders": 0,
  'TEAM NAME::CBK-Columbus Buckeyes': 0,
  'TEAM NAME::CBL-Cleveland Blues': 0,
  'TEAM NAME::CHC-Chicago Cubs': 0,
  'TEAM NAME::CHH-Chicago Whales': 0,
  'TEAM NAME::CHP-Chicago Pirates': 0,
  'TEAM NAME::CHW-Chicago White Sox': 0,
  'TEAM NAME::CIN-Cincinnati Reds': 0,
  "TEAM NAME::CKK-Cincinnati Kelly's Killers": 0,
  'TEAM NAME::CLE-Cleveland Indians': 0,
  'TEAM NAME::CLI-Cleveland Infants': 0,
  'TEAM NAME::CLS-Columbus Solons': 0,
  'TEAM NAME::CLV-Cleveland Spiders': 0,
  'TEAM NAME::CNR-Cincinnati Reds': 0,
  'TEAM NAME::COL-Colorado Rockies': 0,
  'TEAM NAME::COR-Cincinnati Outlaw Reds': 0,
  'TEAM NAME::CPI-Chicago/Pittsburgh (Union League)': 0,
  'TEAM NAME::DET-Detroit Tigers': 0,
  'TEAM NAME::DTN-Detroit Wolverines': 0,
  'TEAM NAME::FLA-Miami Marlins': 0,
  'TEAM NAME::HAR-Hartford Dark Blues': 0,
  'TEAM NAME::HOU-Houston Astros': 0,
  'TEAM NAME::IBL-Indianapolis Blues': 0,
  'TEAM NAME::IHO-Indianapolis Hoosiers': 0,
  'TEAM NAME::IND-Indianapolis Hoosiers': 0,
  'TEAM NAME::KCC-Kansas City Cowboys': 0,
  'TEAM NAME::KCN-Kansas City Cowboys': 0,
  'TEAM NAME::KCP-Kansas City Packers': 0,
  'TEAM NAME::KCR-Kansas City Royals': 0,
  'TEAM NAME::LAD-Los Angeles Dodgers': 0,
  'TEAM NAME::LGR-Louisville Grays': 0,
  'TEAM NAME::LOU-Louisville Colonels': 0,
  'TEAM NAME::MIL-Milwaukee Brewers': 0,
  'TEAM NAME::MIN-Minnesota Twins': 0,
  'TEAM NAME::MLG-Milwaukee Grays': 0,
  'TEAM NAME::NEW-Newark Pepper': 0,
  'TEAM NAME::NYI-New York Giants': 0,
  'TEAM NAME::NYM-New York Mets': 0,
  'TEAM NAME::NYP-New York Metropolitans': 0,
  'TEAM NAME::NYU-New York Mutuals': 0,
  'TEAM NAME::NYY-New York Yankees': 0,
  'TEAM NAME::OAK-Oakland Athletics': 0,
  'TEAM NAME::PBB-Pittsburgh Burghers': 0,
  'TEAM NAME::PBS-Pittsburgh Rebels': 0,
  'TEAM NAME::PHA-Philadelphia Athletics': 0,
  'TEAM NAME::PHI-Philadelphia Phillies': 0,
  'TEAM NAME::PHK-Philadelphia Keystones': 0,
  'TEAM NAME::PHQ-Philadelphia Athletics': 0,
  'TEAM NAME::PIT-Pittsburgh Pirates': 0,
  'TEAM NAME::PRO-Providence Grays': 0,
  'TEAM NAME::ROC-Rochester Broncos': 0,
  'TEAM NAME::SBS-St. Louis Brown Stockings': 0,
  'TEAM NAME::SDP-San Diego Padres': 0,
  'TEAM NAME::SEA-Seattle Mariners': 0,
  'TEAM NAME::SFG-San Francisco Giants': 0,
  'TEAM NAME::SLI-St. Louis Terriers': 0,
  'TEAM NAME::SLM-St. Louis Maroons': 0,
  'TEAM NAME::STL-St. Louis Cardinals': 0,
  'TEAM NAME::SYR-Syracuse Stars': 0,
  'TEAM NAME::SYS-Syracuse Stars': 0,
  'TEAM NAME::TBD-Tampa Bay Rays': 0,
  'TEAM NAME::TEX-Texas Rangers': 0,
  'TEAM NAME::TLM-Toledo Maumees': 0,
  'TEAM NAME::TOL-Toledo Blue Stockings': 0,
  'TEAM NAME::TOR-Toronto Blue Jays': 0,
  'TEAM NAME::TRT-Troy Trojans': 0,
  'TEAM NAME::WAS-Washington Senators': 0,
  'TEAM NAME::WNA-Washington Nationals': 0,
  'TEAM NAME::WNL-Washington Nationals': 0,
  'TEAM NAME::WOR-Worcester Ruby Legs': 0,
  'TEAM NAME::WSN-Washington Nationals': 0,
  'TEAM NAME::WST-Washington Nationals': 0,
  'lgID::AL': 0,
  'lgID::FL': 0,
  'lgID::NL': 1,
  'lgID::PL': 0,
  'lgID::UA': 0,
  'ERA::Dead Ball': 0,
  'ERA::Live Ball': 0,
  'ERA::Integration': 0,
  'ERA::Divisional': 0,
  'ERA::Steroid': 0,
  'ERA::Current': 1},{'AGE': 34,
  'PA': 693,
  'ISP': 0.219,
  'TEAM NAME::ARI-Arizona Diamondbacks': 0,
  'TEAM NAME::ATH-Philadelphia Athletics': 0,
  'TEAM NAME::ATL-Atlanta Braves': 0,
  'TEAM NAME::BAL-Baltimore Orioles': 0,
  'TEAM NAME::BFB-Buffalo Bisons': 0,
  'TEAM NAME::BFL-Buffalo Blues': 0,
  'TEAM NAME::BLO-Baltimore Orioles': 0,
  'TEAM NAME::BLT-Baltimore Terrapins': 0,
  'TEAM NAME::BLU-Baltimore Monumentals': 0,
  'TEAM NAME::BOS-Boston Red Sox': 0,
  'TEAM NAME::BRD-Boston Reds': 0,
  'TEAM NAME::BRG-Brooklyn Gladiators': 0,
  'TEAM NAME::BRS-Boston Reds': 0,
  'TEAM NAME::BTT-Brooklyn Tip-Tops': 0,
  'TEAM NAME::BUF-Buffalo Bisons': 0,
  "TEAM NAME::BWW-Brooklyn Ward's Wonders": 0,
  'TEAM NAME::CBK-Columbus Buckeyes': 0,
  'TEAM NAME::CBL-Cleveland Blues': 0,
  'TEAM NAME::CHC-Chicago Cubs': 0,
  'TEAM NAME::CHH-Chicago Whales': 0,
  'TEAM NAME::CHP-Chicago Pirates': 0,
  'TEAM NAME::CHW-Chicago White Sox': 1,
  'TEAM NAME::CIN-Cincinnati Reds': 0,
  "TEAM NAME::CKK-Cincinnati Kelly's Killers": 0,
  'TEAM NAME::CLE-Cleveland Indians': 0,
  'TEAM NAME::CLI-Cleveland Infants': 0,
  'TEAM NAME::CLS-Columbus Solons': 0,
  'TEAM NAME::CLV-Cleveland Spiders': 0,
  'TEAM NAME::CNR-Cincinnati Reds': 0,
  'TEAM NAME::COL-Colorado Rockies': 0,
  'TEAM NAME::COR-Cincinnati Outlaw Reds': 0,
  'TEAM NAME::CPI-Chicago/Pittsburgh (Union League)': 0,
  'TEAM NAME::DET-Detroit Tigers': 0,
  'TEAM NAME::DTN-Detroit Wolverines': 0,
  'TEAM NAME::FLA-Miami Marlins': 0,
  'TEAM NAME::HAR-Hartford Dark Blues': 0,
  'TEAM NAME::HOU-Houston Astros': 0,
  'TEAM NAME::IBL-Indianapolis Blues': 0,
  'TEAM NAME::IHO-Indianapolis Hoosiers': 0,
  'TEAM NAME::IND-Indianapolis Hoosiers': 0,
  'TEAM NAME::KCC-Kansas City Cowboys': 0,
  'TEAM NAME::KCN-Kansas City Cowboys': 0,
  'TEAM NAME::KCP-Kansas City Packers': 0,
  'TEAM NAME::KCR-Kansas City Royals': 0,
  'TEAM NAME::LAD-Los Angeles Dodgers': 0,
  'TEAM NAME::LGR-Louisville Grays': 0,
  'TEAM NAME::LOU-Louisville Colonels': 0,
  'TEAM NAME::MIL-Milwaukee Brewers': 0,
  'TEAM NAME::MIN-Minnesota Twins': 0,
  'TEAM NAME::MLG-Milwaukee Grays': 0,
  'TEAM NAME::NEW-Newark Pepper': 0,
  'TEAM NAME::NYI-New York Giants': 0,
  'TEAM NAME::NYM-New York Mets': 0,
  'TEAM NAME::NYP-New York Metropolitans': 0,
  'TEAM NAME::NYU-New York Mutuals': 0,
  'TEAM NAME::NYY-New York Yankees': 0,
  'TEAM NAME::OAK-Oakland Athletics': 0,
  'TEAM NAME::PBB-Pittsburgh Burghers': 0,
  'TEAM NAME::PBS-Pittsburgh Rebels': 0,
  'TEAM NAME::PHA-Philadelphia Athletics': 0,
  'TEAM NAME::PHI-Philadelphia Phillies': 0,
  'TEAM NAME::PHK-Philadelphia Keystones': 0,
  'TEAM NAME::PHQ-Philadelphia Athletics': 0,
  'TEAM NAME::PIT-Pittsburgh Pirates': 0,
  'TEAM NAME::PRO-Providence Grays': 0,
  'TEAM NAME::ROC-Rochester Broncos': 0,
  'TEAM NAME::SBS-St. Louis Brown Stockings': 0,
  'TEAM NAME::SDP-San Diego Padres': 0,
  'TEAM NAME::SEA-Seattle Mariners': 0,
  'TEAM NAME::SFG-San Francisco Giants': 0,
  'TEAM NAME::SLI-St. Louis Terriers': 0,
  'TEAM NAME::SLM-St. Louis Maroons': 0,
  'TEAM NAME::STL-St. Louis Cardinals': 0,
  'TEAM NAME::SYR-Syracuse Stars': 0,
  'TEAM NAME::SYS-Syracuse Stars': 0,
  'TEAM NAME::TBD-Tampa Bay Rays': 0,
  'TEAM NAME::TEX-Texas Rangers': 0,
  'TEAM NAME::TLM-Toledo Maumees': 0,
  'TEAM NAME::TOL-Toledo Blue Stockings': 0,
  'TEAM NAME::TOR-Toronto Blue Jays': 0,
  'TEAM NAME::TRT-Troy Trojans': 0,
  'TEAM NAME::WAS-Washington Senators': 0,
  'TEAM NAME::WNA-Washington Nationals': 0,
  'TEAM NAME::WNL-Washington Nationals': 0,
  'TEAM NAME::WOR-Worcester Ruby Legs': 0,
  'TEAM NAME::WSN-Washington Nationals': 0,
  'TEAM NAME::WST-Washington Nationals': 0,
  'lgID::AL': 1,
  'lgID::FL': 0,
  'lgID::NL': 0,
  'lgID::PL': 0,
  'lgID::UA': 0,
  'ERA::Dead Ball': 0,
  'ERA::Live Ball': 0,
  'ERA::Integration': 0,
  'ERA::Divisional': 0,
  'ERA::Steroid': 0,
  'ERA::Current': 1},{'AGE': 25,
  'PA': 661,
  'ISP': 0.324,
  'TEAM NAME::ARI-Arizona Diamondbacks': 0,
  'TEAM NAME::ATH-Philadelphia Athletics': 0,
  'TEAM NAME::ATL-Atlanta Braves': 0,
  'TEAM NAME::BAL-Baltimore Orioles': 0,
  'TEAM NAME::BFB-Buffalo Bisons': 0,
  'TEAM NAME::BFL-Buffalo Blues': 0,
  'TEAM NAME::BLO-Baltimore Orioles': 0,
  'TEAM NAME::BLT-Baltimore Terrapins': 0,
  'TEAM NAME::BLU-Baltimore Monumentals': 0,
  'TEAM NAME::BOS-Boston Red Sox': 0,
  'TEAM NAME::BRD-Boston Reds': 0,
  'TEAM NAME::BRG-Brooklyn Gladiators': 0,
  'TEAM NAME::BRS-Boston Reds': 0,
  'TEAM NAME::BTT-Brooklyn Tip-Tops': 0,
  'TEAM NAME::BUF-Buffalo Bisons': 0,
  "TEAM NAME::BWW-Brooklyn Ward's Wonders": 0,
  'TEAM NAME::CBK-Columbus Buckeyes': 0,
  'TEAM NAME::CBL-Cleveland Blues': 0,
  'TEAM NAME::CHC-Chicago Cubs': 0,
  'TEAM NAME::CHH-Chicago Whales': 0,
  'TEAM NAME::CHP-Chicago Pirates': 0,
  'TEAM NAME::CHW-Chicago White Sox': 0,
  'TEAM NAME::CIN-Cincinnati Reds': 0,
  "TEAM NAME::CKK-Cincinnati Kelly's Killers": 0,
  'TEAM NAME::CLE-Cleveland Indians': 0,
  'TEAM NAME::CLI-Cleveland Infants': 0,
  'TEAM NAME::CLS-Columbus Solons': 0,
  'TEAM NAME::CLV-Cleveland Spiders': 0,
  'TEAM NAME::CNR-Cincinnati Reds': 0,
  'TEAM NAME::COL-Colorado Rockies': 0,
  'TEAM NAME::COR-Cincinnati Outlaw Reds': 0,
  'TEAM NAME::CPI-Chicago/Pittsburgh (Union League)': 0,
  'TEAM NAME::DET-Detroit Tigers': 0,
  'TEAM NAME::DTN-Detroit Wolverines': 0,
  'TEAM NAME::FLA-Miami Marlins': 0,
  'TEAM NAME::HAR-Hartford Dark Blues': 0,
  'TEAM NAME::HOU-Houston Astros': 0,
  'TEAM NAME::IBL-Indianapolis Blues': 0,
  'TEAM NAME::IHO-Indianapolis Hoosiers': 0,
  'TEAM NAME::IND-Indianapolis Hoosiers': 0,
  'TEAM NAME::KCC-Kansas City Cowboys': 0,
  'TEAM NAME::KCN-Kansas City Cowboys': 0,
  'TEAM NAME::KCP-Kansas City Packers': 0,
  'TEAM NAME::KCR-Kansas City Royals': 0,
  'TEAM NAME::LAD-Los Angeles Dodgers': 1,
  'TEAM NAME::LGR-Louisville Grays': 0,
  'TEAM NAME::LOU-Louisville Colonels': 0,
  'TEAM NAME::MIL-Milwaukee Brewers': 0,
  'TEAM NAME::MIN-Minnesota Twins': 0,
  'TEAM NAME::MLG-Milwaukee Grays': 0,
  'TEAM NAME::NEW-Newark Pepper': 0,
  'TEAM NAME::NYI-New York Giants': 0,
  'TEAM NAME::NYM-New York Mets': 0,
  'TEAM NAME::NYP-New York Metropolitans': 0,
  'TEAM NAME::NYU-New York Mutuals': 0,
  'TEAM NAME::NYY-New York Yankees': 0,
  'TEAM NAME::OAK-Oakland Athletics': 0,
  'TEAM NAME::PBB-Pittsburgh Burghers': 0,
  'TEAM NAME::PBS-Pittsburgh Rebels': 0,
  'TEAM NAME::PHA-Philadelphia Athletics': 0,
  'TEAM NAME::PHI-Philadelphia Phillies': 0,
  'TEAM NAME::PHK-Philadelphia Keystones': 0,
  'TEAM NAME::PHQ-Philadelphia Athletics': 0,
  'TEAM NAME::PIT-Pittsburgh Pirates': 0,
  'TEAM NAME::PRO-Providence Grays': 0,
  'TEAM NAME::ROC-Rochester Broncos': 0,
  'TEAM NAME::SBS-St. Louis Brown Stockings': 0,
  'TEAM NAME::SDP-San Diego Padres': 0,
  'TEAM NAME::SEA-Seattle Mariners': 0,
  'TEAM NAME::SFG-San Francisco Giants': 0,
  'TEAM NAME::SLI-St. Louis Terriers': 0,
  'TEAM NAME::SLM-St. Louis Maroons': 0,
  'TEAM NAME::STL-St. Louis Cardinals': 0,
  'TEAM NAME::SYR-Syracuse Stars': 0,
  'TEAM NAME::SYS-Syracuse Stars': 0,
  'TEAM NAME::TBD-Tampa Bay Rays': 0,
  'TEAM NAME::TEX-Texas Rangers': 0,
  'TEAM NAME::TLM-Toledo Maumees': 0,
  'TEAM NAME::TOL-Toledo Blue Stockings': 0,
  'TEAM NAME::TOR-Toronto Blue Jays': 0,
  'TEAM NAME::TRT-Troy Trojans': 0,
  'TEAM NAME::WAS-Washington Senators': 0,
  'TEAM NAME::WNA-Washington Nationals': 0,
  'TEAM NAME::WNL-Washington Nationals': 0,
  'TEAM NAME::WOR-Worcester Ruby Legs': 0,
  'TEAM NAME::WSN-Washington Nationals': 0,
  'TEAM NAME::WST-Washington Nationals': 0,
  'lgID::AL': 0,
  'lgID::FL': 0,
  'lgID::NL': 1,
  'lgID::PL': 0,
  'lgID::UA': 0,
  'ERA::Dead Ball': 0,
  'ERA::Live Ball': 0,
  'ERA::Integration': 0,
  'ERA::Divisional': 0,
  'ERA::Steroid': 0,
  'ERA::Current': 1},{'AGE': 28,
  'PA': 285,
  'ISP': 0.192,
  'TEAM NAME::ARI-Arizona Diamondbacks': 0,
  'TEAM NAME::ATH-Philadelphia Athletics': 0,
  'TEAM NAME::ATL-Atlanta Braves': 0,
  'TEAM NAME::BAL-Baltimore Orioles': 0,
  'TEAM NAME::BFB-Buffalo Bisons': 0,
  'TEAM NAME::BFL-Buffalo Blues': 0,
  'TEAM NAME::BLO-Baltimore Orioles': 0,
  'TEAM NAME::BLT-Baltimore Terrapins': 0,
  'TEAM NAME::BLU-Baltimore Monumentals': 0,
  'TEAM NAME::BOS-Boston Red Sox': 0,
  'TEAM NAME::BRD-Boston Reds': 0,
  'TEAM NAME::BRG-Brooklyn Gladiators': 0,
  'TEAM NAME::BRS-Boston Reds': 0,
  'TEAM NAME::BTT-Brooklyn Tip-Tops': 0,
  'TEAM NAME::BUF-Buffalo Bisons': 0,
  "TEAM NAME::BWW-Brooklyn Ward's Wonders": 0,
  'TEAM NAME::CBK-Columbus Buckeyes': 0,
  'TEAM NAME::CBL-Cleveland Blues': 0,
  'TEAM NAME::CHC-Chicago Cubs': 0,
  'TEAM NAME::CHH-Chicago Whales': 0,
  'TEAM NAME::CHP-Chicago Pirates': 0,
  'TEAM NAME::CHW-Chicago White Sox': 0,
  'TEAM NAME::CIN-Cincinnati Reds': 0,
  "TEAM NAME::CKK-Cincinnati Kelly's Killers": 0,
  'TEAM NAME::CLE-Cleveland Indians': 0,
  'TEAM NAME::CLI-Cleveland Infants': 0,
  'TEAM NAME::CLS-Columbus Solons': 0,
  'TEAM NAME::CLV-Cleveland Spiders': 0,
  'TEAM NAME::CNR-Cincinnati Reds': 0,
  'TEAM NAME::COL-Colorado Rockies': 0,
  'TEAM NAME::COR-Cincinnati Outlaw Reds': 0,
  'TEAM NAME::CPI-Chicago/Pittsburgh (Union League)': 0,
  'TEAM NAME::DET-Detroit Tigers': 0,
  'TEAM NAME::DTN-Detroit Wolverines': 0,
  'TEAM NAME::FLA-Miami Marlins': 0,
  'TEAM NAME::HAR-Hartford Dark Blues': 0,
  'TEAM NAME::HOU-Houston Astros': 0,
  'TEAM NAME::IBL-Indianapolis Blues': 0,
  'TEAM NAME::IHO-Indianapolis Hoosiers': 0,
  'TEAM NAME::IND-Indianapolis Hoosiers': 0,
  'TEAM NAME::KCC-Kansas City Cowboys': 0,
  'TEAM NAME::KCN-Kansas City Cowboys': 0,
  'TEAM NAME::KCP-Kansas City Packers': 0,
  'TEAM NAME::KCR-Kansas City Royals': 0,
  'TEAM NAME::LAD-Los Angeles Dodgers': 0,
  'TEAM NAME::LGR-Louisville Grays': 0,
  'TEAM NAME::LOU-Louisville Colonels': 0,
  'TEAM NAME::MIL-Milwaukee Brewers': 0,
  'TEAM NAME::MIN-Minnesota Twins': 0,
  'TEAM NAME::MLG-Milwaukee Grays': 0,
  'TEAM NAME::NEW-Newark Pepper': 0,
  'TEAM NAME::NYI-New York Giants': 0,
  'TEAM NAME::NYM-New York Mets': 0,
  'TEAM NAME::NYP-New York Metropolitans': 0,
  'TEAM NAME::NYU-New York Mutuals': 0,
  'TEAM NAME::NYY-New York Yankees': 0,
  'TEAM NAME::OAK-Oakland Athletics': 0,
  'TEAM NAME::PBB-Pittsburgh Burghers': 0,
  'TEAM NAME::PBS-Pittsburgh Rebels': 0,
  'TEAM NAME::PHA-Philadelphia Athletics': 0,
  'TEAM NAME::PHI-Philadelphia Phillies': 0,
  'TEAM NAME::PHK-Philadelphia Keystones': 0,
  'TEAM NAME::PHQ-Philadelphia Athletics': 0,
  'TEAM NAME::PIT-Pittsburgh Pirates': 1,
  'TEAM NAME::PRO-Providence Grays': 0,
  'TEAM NAME::ROC-Rochester Broncos': 0,
  'TEAM NAME::SBS-St. Louis Brown Stockings': 0,
  'TEAM NAME::SDP-San Diego Padres': 0,
  'TEAM NAME::SEA-Seattle Mariners': 0,
  'TEAM NAME::SFG-San Francisco Giants': 0,
  'TEAM NAME::SLI-St. Louis Terriers': 0,
  'TEAM NAME::SLM-St. Louis Maroons': 0,
  'TEAM NAME::STL-St. Louis Cardinals': 0,
  'TEAM NAME::SYR-Syracuse Stars': 0,
  'TEAM NAME::SYS-Syracuse Stars': 0,
  'TEAM NAME::TBD-Tampa Bay Rays': 0,
  'TEAM NAME::TEX-Texas Rangers': 0,
  'TEAM NAME::TLM-Toledo Maumees': 0,
  'TEAM NAME::TOL-Toledo Blue Stockings': 0,
  'TEAM NAME::TOR-Toronto Blue Jays': 0,
  'TEAM NAME::TRT-Troy Trojans': 0,
  'TEAM NAME::WAS-Washington Senators': 0,
  'TEAM NAME::WNA-Washington Nationals': 0,
  'TEAM NAME::WNL-Washington Nationals': 0,
  'TEAM NAME::WOR-Worcester Ruby Legs': 0,
  'TEAM NAME::WSN-Washington Nationals': 0,
  'TEAM NAME::WST-Washington Nationals': 0,
  'lgID::AL': 0,
  'lgID::FL': 0,
  'lgID::NL': 1,
  'lgID::PL': 0,
  'lgID::UA': 0,
  'ERA::Dead Ball': 0,
  'ERA::Live Ball': 0,
  'ERA::Integration': 0,
  'ERA::Divisional': 0,
  'ERA::Steroid': 0,
  'ERA::Current': 1},{'AGE': 29,
  'PA': 447,
  'ISP': 0.268,
  'TEAM NAME::ARI-Arizona Diamondbacks': 0,
  'TEAM NAME::ATH-Philadelphia Athletics': 0,
  'TEAM NAME::ATL-Atlanta Braves': 0,
  'TEAM NAME::BAL-Baltimore Orioles': 0,
  'TEAM NAME::BFB-Buffalo Bisons': 0,
  'TEAM NAME::BFL-Buffalo Blues': 0,
  'TEAM NAME::BLO-Baltimore Orioles': 0,
  'TEAM NAME::BLT-Baltimore Terrapins': 0,
  'TEAM NAME::BLU-Baltimore Monumentals': 0,
  'TEAM NAME::BOS-Boston Red Sox': 0,
  'TEAM NAME::BRD-Boston Reds': 0,
  'TEAM NAME::BRG-Brooklyn Gladiators': 0,
  'TEAM NAME::BRS-Boston Reds': 0,
  'TEAM NAME::BTT-Brooklyn Tip-Tops': 0,
  'TEAM NAME::BUF-Buffalo Bisons': 0,
  "TEAM NAME::BWW-Brooklyn Ward's Wonders": 0,
  'TEAM NAME::CBK-Columbus Buckeyes': 0,
  'TEAM NAME::CBL-Cleveland Blues': 0,
  'TEAM NAME::CHC-Chicago Cubs': 0,
  'TEAM NAME::CHH-Chicago Whales': 0,
  'TEAM NAME::CHP-Chicago Pirates': 0,
  'TEAM NAME::CHW-Chicago White Sox': 0,
  'TEAM NAME::CIN-Cincinnati Reds': 0,
  "TEAM NAME::CKK-Cincinnati Kelly's Killers": 0,
  'TEAM NAME::CLE-Cleveland Indians': 0,
  'TEAM NAME::CLI-Cleveland Infants': 0,
  'TEAM NAME::CLS-Columbus Solons': 0,
  'TEAM NAME::CLV-Cleveland Spiders': 0,
  'TEAM NAME::CNR-Cincinnati Reds': 0,
  'TEAM NAME::COL-Colorado Rockies': 0,
  'TEAM NAME::COR-Cincinnati Outlaw Reds': 0,
  'TEAM NAME::CPI-Chicago/Pittsburgh (Union League)': 0,
  'TEAM NAME::DET-Detroit Tigers': 0,
  'TEAM NAME::DTN-Detroit Wolverines': 0,
  'TEAM NAME::FLA-Miami Marlins': 0,
  'TEAM NAME::HAR-Hartford Dark Blues': 0,
  'TEAM NAME::HOU-Houston Astros': 0,
  'TEAM NAME::IBL-Indianapolis Blues': 0,
  'TEAM NAME::IHO-Indianapolis Hoosiers': 0,
  'TEAM NAME::IND-Indianapolis Hoosiers': 0,
  'TEAM NAME::KCC-Kansas City Cowboys': 0,
  'TEAM NAME::KCN-Kansas City Cowboys': 0,
  'TEAM NAME::KCP-Kansas City Packers': 0,
  'TEAM NAME::KCR-Kansas City Royals': 0,
  'TEAM NAME::LAD-Los Angeles Dodgers': 0,
  'TEAM NAME::LGR-Louisville Grays': 0,
  'TEAM NAME::LOU-Louisville Colonels': 0,
  'TEAM NAME::MIL-Milwaukee Brewers': 0,
  'TEAM NAME::MIN-Minnesota Twins': 0,
  'TEAM NAME::MLG-Milwaukee Grays': 0,
  'TEAM NAME::NEW-Newark Pepper': 0,
  'TEAM NAME::NYI-New York Giants': 0,
  'TEAM NAME::NYM-New York Mets': 0,
  'TEAM NAME::NYP-New York Metropolitans': 0,
  'TEAM NAME::NYU-New York Mutuals': 0,
  'TEAM NAME::NYY-New York Yankees': 1,
  'TEAM NAME::OAK-Oakland Athletics': 0,
  'TEAM NAME::PBB-Pittsburgh Burghers': 0,
  'TEAM NAME::PBS-Pittsburgh Rebels': 0,
  'TEAM NAME::PHA-Philadelphia Athletics': 0,
  'TEAM NAME::PHI-Philadelphia Phillies': 0,
  'TEAM NAME::PHK-Philadelphia Keystones': 0,
  'TEAM NAME::PHQ-Philadelphia Athletics': 0,
  'TEAM NAME::PIT-Pittsburgh Pirates': 0,
  'TEAM NAME::PRO-Providence Grays': 0,
  'TEAM NAME::ROC-Rochester Broncos': 0,
  'TEAM NAME::SBS-St. Louis Brown Stockings': 0,
  'TEAM NAME::SDP-San Diego Padres': 0,
  'TEAM NAME::SEA-Seattle Mariners': 0,
  'TEAM NAME::SFG-San Francisco Giants': 0,
  'TEAM NAME::SLI-St. Louis Terriers': 0,
  'TEAM NAME::SLM-St. Louis Maroons': 0,
  'TEAM NAME::STL-St. Louis Cardinals': 0,
  'TEAM NAME::SYR-Syracuse Stars': 0,
  'TEAM NAME::SYS-Syracuse Stars': 0,
  'TEAM NAME::TBD-Tampa Bay Rays': 0,
  'TEAM NAME::TEX-Texas Rangers': 0,
  'TEAM NAME::TLM-Toledo Maumees': 0,
  'TEAM NAME::TOL-Toledo Blue Stockings': 0,
  'TEAM NAME::TOR-Toronto Blue Jays': 0,
  'TEAM NAME::TRT-Troy Trojans': 0,
  'TEAM NAME::WAS-Washington Senators': 0,
  'TEAM NAME::WNA-Washington Nationals': 0,
  'TEAM NAME::WNL-Washington Nationals': 0,
  'TEAM NAME::WOR-Worcester Ruby Legs': 0,
  'TEAM NAME::WSN-Washington Nationals': 0,
  'TEAM NAME::WST-Washington Nationals': 0,
  'lgID::AL': 1,
  'lgID::FL': 0,
  'lgID::NL': 0,
  'lgID::PL': 0,
  'lgID::UA': 0,
  'ERA::Dead Ball': 0,
  'ERA::Live Ball': 0,
  'ERA::Integration': 0,
  'ERA::Divisional': 0,
  'ERA::Steroid': 0,
  'ERA::Current': 1}]

In [302]:
pdSamplebbstats = pd.DataFrame.from_dict(samplebbstats)
pdSamplebbstats

,AGE,PA,ISP,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,TEAM NAME::BLO-Baltimore Orioles,...,lgID::FL,lgID::NL,lgID::PL,lgID::UA,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current
0,31,692,0.254,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,34,693,0.219,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,25,661,0.324,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,28,285,0.192,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
4,29,447,0.268,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [303]:
predictions = lr.predict(pdSamplebbstats)
predictions

array([0.91992889, 0.87626054, 1.01748799, 0.77864575, 0.91121328])

In [304]:
pdPredictedbbstats = pdSamplebbstats.copy()
pdPredictedbbstats['Predicted'] = predictions

In [305]:
pdPredictedbbstats['Player'] = ['Freddie Freeman','Jose Abreu','Clay Bellinger','Jose Osuna','Aaron Judge']
pdPredictedbbstats

,AGE,PA,ISP,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,TEAM NAME::BLO-Baltimore Orioles,...,lgID::PL,lgID::UA,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current,Predicted,Player
0,31,692,0.254,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0.919929,Freddie Freeman
1,34,693,0.219,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0.876261,Jose Abreu
2,25,661,0.324,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1.017488,Clay Bellinger
3,28,285,0.192,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0.778646,Jose Osuna
4,29,447,0.268,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0.911213,Aaron Judge

# Ridge Regression Model

In [306]:
rr = Ridge(solver="svd")
rr

Ridge(solver='svd')

In [307]:
rr.fit(X_train, y_train)

Ridge(solver='svd')

In [308]:
rr.score(X_train, y_train)

0.7190813455496499

In [309]:
rr.score(X_test, y_test)

0.7096934838291138

In [310]:
predictionsrr = rr.predict(X_test)
printMetrics(y_test, predictionsrr)

Score: 0.71
MAE: 0.05
RMSE: 0.06
r2: 0.71

In [311]:
pdSamplebbstats

,AGE,PA,ISP,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,TEAM NAME::BLO-Baltimore Orioles,...,lgID::FL,lgID::NL,lgID::PL,lgID::UA,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current
0,31,692,0.254,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,34,693,0.219,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,25,661,0.324,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,28,285,0.192,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
4,29,447,0.268,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [312]:
predictionsrr = rr.predict(pdSamplebbstats)
predictionsrr

array([0.91872544, 0.87550197, 1.01441944, 0.77760519, 0.90915391])

In [313]:
pdPredictedbbstatsrr = pdSamplebbstats.copy()
pdPredictedbbstatsrr['Predicted'] = predictionsrr

In [314]:
pdPredictedbbstatsrr['Player'] = ['Freddie Freeman','Jose Abreu','Clay Bellinger','Jose Osuna','Aaron Judge']
pdPredictedbbstatsrr

,AGE,PA,ISP,TEAM NAME::ARI-Arizona Diamondbacks,TEAM NAME::ATH-Philadelphia Athletics,TEAM NAME::ATL-Atlanta Braves,TEAM NAME::BAL-Baltimore Orioles,TEAM NAME::BFB-Buffalo Bisons,TEAM NAME::BFL-Buffalo Blues,TEAM NAME::BLO-Baltimore Orioles,...,lgID::PL,lgID::UA,ERA::Dead Ball,ERA::Live Ball,ERA::Integration,ERA::Divisional,ERA::Steroid,ERA::Current,Predicted,Player
0,31,692,0.254,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0.918725,Freddie Freeman
1,34,693,0.219,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0.875502,Jose Abreu
2,25,661,0.324,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1.014419,Clay Bellinger
3,28,285,0.192,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0.777605,Jose Osuna
4,29,447,0.268,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0.909154,Aaron Judge