In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pandas as pdb

In [3]:
baseballstats = pd.read_csv("https://raw.githubusercontent.com/zoberender/Python-Group-Project/master/Batting.csv")
#It is important to convert NaN to 0 to get calculations to function correctly
baseballstats['IBB'] = baseballstats['IBB'].fillna(0)
baseballstats['HBP'] = baseballstats['HBP'].fillna(0)
baseballstats['SH'] = baseballstats['SH'].fillna(0)
baseballstats['SF'] = baseballstats['SF'].fillna(0)
# Create new column to calculate average
baseballstats["AVG"] = baseballstats["H"]/baseballstats["AB"]
# Create new column to calculate total bases
baseballstats["TB"] = baseballstats["H"] - baseballstats["2B"] - baseballstats["3B"] - baseballstats["HR"] + 2*baseballstats["2B"] + 3*baseballstats["3B"]+4*baseballstats["HR"]
# Slugging is Total Bases/At bats
baseballstats["SLG"] = baseballstats["TB"]/baseballstats["AB"]
#Plate Appearances to calculate OBP
baseballstats["PA"] = baseballstats["AB"] + baseballstats["BB"] + baseballstats["HBP"] + baseballstats["SF"]
#On Base Percentage = Times on base/Plat Appearances
baseballstats["OBP"] = (baseballstats["H"]+baseballstats["BB"]+baseballstats["HBP"])/baseballstats["PA"]
#OBP + SLUGGING IS A GREAT WAY TO MEASURE OVERALL PLAYER VALUE
baseballstats["OPS"] = baseballstats["OBP"] + baseballstats["SLG"]
#ISOLATED POWER IS A WAY TO MEASURE A PLAYER'S OVERALL POWER WHY TAKING OUT THE IMPACT OF BATTING AVERAGE
baseballstats['ISP'] = baseballstats['SLG'] - baseballstats['AVG']
baseballstats

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,SH,SF,GIDP,AVG,TB,SLG,PA,OBP,OPS,ISP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,...,0.0,0.0,0.0,0.000000,0,0.000000,4.0,0.000000,0.000000,0.000000
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,...,0.0,0.0,0.0,0.271186,38,0.322034,122.0,0.295082,0.617116,0.050847
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,...,0.0,0.0,1.0,0.291971,54,0.394161,139.0,0.302158,0.696319,0.102190
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,...,0.0,0.0,0.0,0.330827,64,0.481203,133.0,0.330827,0.812030,0.150376
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,...,0.0,0.0,0.0,0.325000,56,0.466667,122.0,0.336066,0.802732,0.141667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108784,zimmebr02,2020,1,BAL,AL,2,0,0,0,0,...,0.0,0.0,0.0,NaN,0,NaN,0.0,NaN,NaN,NaN
108785,zimmejo02,2020,1,DET,AL,3,0,0,0,0,...,0.0,0.0,0.0,NaN,0,NaN,0.0,NaN,NaN,NaN
108786,zimmeky01,2020,1,KCA,AL,16,0,0,0,0,...,0.0,0.0,0.0,NaN,0,NaN,0.0,NaN,NaN,NaN
108787,zuberty01,2020,1,KCA,AL,23,0,0,0,0,...,0.0,0.0,0.0,NaN,0,NaN,0.0,NaN,NaN,NaN
108788,zuninmi01,2020,1,TBA,AL,28,75,8,11,4,...,0.0,0.0,0.0,0.146667,27,0.360000,84.0,0.238095,0.598095,0.213333